# MCC and MNC values of the gNB
plmn:
  mcc: 1
  mnc: 1

# ID of the gNB inside of its PLMN
gnbId: 1

# Tracking Area Code (TAC)
tac: 117

# NR Cell Identity (NCI)
nci: '0000000100'

# gNB's local IP address for N2 interface.
ngapIp: 127.0.0.1

# gNB's local IP address for N3 interface.
gtpIp: 127.0.0.1

# List of AMF address information
amfConfigs:
  - ngapIp: 10.154.14.19
    ngapPort: 38412

# List of NSSAIs supported by this gNB
nssais:
  - sst: '0x01'

# Indicates whether or not SCTP stream number errors should be ignored.
ignoreStreamIds: true
